### ISSUE TITLE
Loads slowly

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#330]
I know there's a lot to load, but is there any way to make it load faster? One of the new faculty mentioned the slow loading in their feedback.

**Comment by sandbergja** [comment]
Were they commenting on the search results?  Or the main page?

**Comment by mwillihooper** [comment]
Search results--when you're doing or modifying a search. I've been noticing with patrons (and myself) that sometimes we don't notice the blue loading bar below the purple and keep hitting search again. Is there a way to make it very obvious that it's loading?

**Comment by sandbergja** [comment]
After performance improvements in both the code and the production environment, the search results page is taking 2-3 seconds to load for me today.  Roughly 1 second of that is waiting for results from Ebsco.  Some improvements remain to be done in the 1-2 seconds that FindIt can directly control; I will track those on their own tickets.

I will push a change to make the loading bar more noticeable shortly, and then close this ticket.
