### ISSUE TITLE
Publication date slider doesn't show up when limit to articles

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#375]
The lovely publication date slider that's an option for limiting books doesn't show up when limiting articles. It is clunky to limit to one year at a time (current option), and student told me they assumed that it would limit to everything from that date forward.

**Comment by sandbergja** [comment]
I'm already tracking this as issue #260, hopefully to be addressed Winter Term -- I'll be sure to keep you posted on it, @mwillihooper
