### ISSUE TITLE
No way to get back to original article/book page

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#376]
Once you limit to books, it is not apparent how to see articles as well without starting the search over again.

![image](https://user-images.githubusercontent.com/10551463/98864671-1a5fbc80-241f-11eb-91af-c30d1ba8ff76.png)

**Comment by sandbergja** [comment]
@mwillihooper: one idea I'd had was to add a [Books and videos (x)] or [Articles (x)] limiter, right between the "Start Over" button and the [Chocolate Dogs (x)] limiter in your screenshot.  Then, patrons could click on the (x) to return to that initial search results screen.  Thoughts?

**Comment by mwillihooper** [comment]
Yes, I like that!
