### ISSUE TITLE
Publication Year under Article filter doesn't show all publication years

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#390]
![image](https://user-images.githubusercontent.com/10551463/99742243-f425c680-2a87-11eb-9a4c-e6ebd611090a.png)

Did a search and there were 133 articles, but the Publication Year limiter only showed three publications. I went to look to see if I could sort by newest first, but I don't think that's an option, either.

**Comment by sandbergja** [comment]
closing, because this will be handled by #444
