### ISSUE TITLE
Links to Newsbank going to Newsbank homepage

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#391]
When I click on a result in Newsbank (https://libfind.linnbenton.edu:4430/articles/edsnbk/168F3AF40E9E6A98), it takes me to the Newsbank landing page instead of the article.

**Comment by sandbergja** [comment]
Issue reported to Newsbank and EBSCO -- we'll see what they have to say.

**Comment by sandbergja** [comment]
EBSCO and Newsbank fixed this issue!
