### ISSUE TITLE
Link to Academic Article showing PDF reader rather than EBSCO interface

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#430]
When I clicked on "Academic Article" in FindIt for the article below, it took me directly to a PDF from EBSCO with none of the context/surrounding options. It was kind of nice to go directly to the PDF, but if I wanted to permalink it or cite it, or see subject terms/abstract, I wouldn't be able to do that. This doesn't seem to be happening with other articles. Not sure why it's happening with this one.
![image](https://user-images.githubusercontent.com/10551463/114735457-0a177a80-9cfa-11eb-8b96-a0a2b4064281.png)
![image](https://user-images.githubusercontent.com/10551463/114735564-274c4900-9cfa-11eb-91e2-2f65db9a73ef.png)

**Comment by sandbergja** [comment]
This will be resolved as part of the work on FindIt 3.  Subject terms, abstract, citations will be available for articles on the FindIt page, so we can take people directly to PDFs.  Thanks, Michaela.
